//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMT.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FunctionTemplate&gt;
        ///    &lt;AxClass
        ///        xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///        &lt;Name&gt;$ClassPrefix$Contract&lt;/Name&gt;
        ///        &lt;SourceCode&gt;
        ///            &lt;Declaration&gt;
        ///                &lt;![CDATA[
        ////// &lt;summary&gt;
        ///$Comment$
        ////// Contract class of the report
        ////// &lt;/summary&gt;
        ///[
        ///    DataContractAttribute,
        ///    //Register a UIBuilder, it is optional, if you have some custom function for the dialog fields you could register a UIBuilder
        ///    SysOperationCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Report_Classes {
            get {
                return ResourceManager.GetString("Report_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FunctionTemplate&gt;
        ///    &lt;AxClass
        ///        xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///        &lt;Name&gt;$ClassPrefix$Contract&lt;/Name&gt;
        ///        &lt;SourceCode&gt;
        ///            &lt;Declaration&gt;
        ///                &lt;![CDATA[
        ////// &lt;summary&gt;
        ///$Comment$
        ////// Contract class of the report
        ////// &lt;/summary&gt;
        ///[
        ///    DataContractAttribute,
        ///    //Register a UIBuilder, it is optional, if you have some custom function for the dialog fields you could register a UIBuilder
        ///    SysOperationCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Report_Classes_with_Query {
            get {
                return ResourceManager.GetString("Report_Classes_with_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FunctionTemplate&gt;
        ///    &lt;AxClass
        ///        xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///        &lt;Name&gt;$ClassPrefix$Batch&lt;/Name&gt;
        ///        &lt;SourceCode&gt;
        ///            &lt;Declaration&gt;
        ///                &lt;![CDATA[
        ////// &lt;summary&gt;
        ///$Comment$
        ////// Batch job to process raw material migration
        ////// &lt;/summary&gt;
        ///class $ClassPrefix$Batch extends RunBaseBatch implements BatchRetryable
        ///{
        ///    // Packed variables
        ///    TransDate       gTransDate;
        ///    CustAccount     gCustAccount;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RunBaseBatch {
            get {
                return ResourceManager.GetString("RunBaseBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FunctionTemplate&gt;
        ///    &lt;AxClass
        ///        xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///        &lt;Name&gt;$ClassPrefix$Batch&lt;/Name&gt;
        ///        &lt;SourceCode&gt;
        ///            &lt;Declaration&gt;
        ///                &lt;![CDATA[
        ////// &lt;summary&gt;
        ///$Comment$
        ////// Batch job to process raw material migration
        ////// &lt;/summary&gt;
        ///class $ClassPrefix$Batch extends RunBaseBatch implements BatchRetryable
        ///{
        ///    // Packed variables
        ///    TransDate       gTransDate;
        ///    CustAccount     gCustAccount;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RunBaseBatch_with_Query {
            get {
                return ResourceManager.GetString("RunBaseBatch_with_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FunctionTemplate&gt;
        ///    &lt;AxClass
        ///        xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///        &lt;Name&gt;$ClassPrefix$Contract&lt;/Name&gt;
        ///        &lt;SourceCode&gt;
        ///            &lt;Declaration&gt;
        ///                &lt;![CDATA[
        ////// &lt;summary&gt;
        ///$Comment$
        ////// This class used to prepare parameter for service.
        ////// &lt;/summary&gt;
        ///[
        ///    DataContractAttribute,
        ///    //Register a UIBuilder, it is optional, if you have some custom function for the dialog fields you could register a UIBuilde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SysOperation {
            get {
                return ResourceManager.GetString("SysOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FunctionTemplate&gt;
        ///    &lt;AxClass
        ///        xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///        &lt;Name&gt;$ClassPrefix$Contract&lt;/Name&gt;
        ///        &lt;SourceCode&gt;
        ///            &lt;Declaration&gt;
        ///                &lt;![CDATA[
        ////// &lt;summary&gt;
        ///$Comment$
        ////// This class used to prepare parameter for service.
        ////// &lt;/summary&gt;
        ///[
        ///    DataContractAttribute,
        ///    //Register a UIBuilder, it is optional, if you have some custom function for the dialog fields you could register a UIBuilde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SysOperation_with_Query {
            get {
                return ResourceManager.GetString("SysOperation_with_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FunctionTemplate&gt;
        ///	&lt;AxDataEntityView xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///		&lt;Name&gt;$CustomerPrefix$$ObjectName$Entity&lt;/Name&gt;
        ///		&lt;SourceCode&gt;
        ///			&lt;Declaration&gt;
        ///				&lt;![CDATA[
        ////// &lt;summary&gt;
        ///$Comment$
        ////// This table was deisgned to store the data of $ObjectLabel$
        ////// &lt;/summary&gt;
        ///public class $CustomerPrefix$$ObjectName$Entity extends common
        ///{
        ///}
        ///
        ///]]&gt;
        ///			&lt;/Declaration&gt;
        ///			&lt;Methods /&gt;
        ///		&lt;/SourceCode&gt;
        ///		&lt;FormRef&gt;$CustomerPrefix$$ObjectName$Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_Form_Entity_suit_for_one_field {
            get {
                return ResourceManager.GetString("Table_Form_Entity_suit_for_one_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TableFieldsBuilderTemplateV1 {
            get {
                object obj = ResourceManager.GetObject("TableFieldsBuilderTemplateV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TableFieldsBuilderTemplateV11 {
            get {
                object obj = ResourceManager.GetObject("TableFieldsBuilderTemplateV11", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
